version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build Nuxt.js app
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .nuxt
            - static
            - node_modules
      - store_artifacts:
          path: .nuxt
          destination: .nuxt
      - store_artifacts:
          path: static
          destination: static
  deploy:
    docker:
      - image: cimg/node:16
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Install Vercel CLI
          command: npm install -g vercel
      - run:
          name: Deploy to Vercel
          command: vercel deploy --prod
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
