version: 2.1

jobs:
  preview_deployment:
    docker:
      - image: circleci/node:latest
    environment:
      VERCEL_ORG_ID: $VERCEL_ORG_ID
      VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID
    parallelism: 2  # Number of parallel jobs
    steps:
      - checkout
      - run:
          name: Install Vercel CLI
          command: npm install -g vercel
      - run:
          name: Pull Vercel Environment Information
          command: vercel pull --yes --environment preview --token $VERCEL_TOKEN --force
      - run:
          name: Build Project Artifacts
          command: vercel build --token $VERCEL_TOKEN --force
      - run:
          name: Deploy Project Artifacts to Vercel
          command: vercel deploy --prod --token $VERCEL_TOKEN --force

  production_deployment:
    docker:
      - image: circleci/node:latest
    environment:
      VERCEL_ORG_ID: $VERCEL_ORG_ID
      VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID
    parallelism: 2  # Number of parallel jobs
    steps:
      - checkout
      - run:
          name: Install Vercel CLI
          command: npm install -g vercel
      - run:
          name: Pull Vercel Environment Information
          command: vercel pull --yes --environment production --token $VERCEL_TOKEN --force
      - run:
          name: Build Project Artifacts
          command: vercel build --prod --token $VERCEL_TOKEN --force
      - run:
          name: Deploy Project Artifacts to Vercel
          command: vercel deploy --prod --token $VERCEL_TOKEN --force

workflows:
  version: 2
  preview_and_production:
    jobs:
      - preview_deployment:
          filters:
            branches:
              ignore: /main/
      - production_deployment:
          filters:
            branches:
              only: /main/
